# Main bg
theme[main_bg]="#21170d"

# Main text color
theme[main_fg]="#aa7446"

# Title color for boxes
theme[title]="#aa7446"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#c5b191"

# Background color of selected item in processes box
theme[selected_bg]="#ad9066"

# Foreground color of selected item in processes box
theme[selected_fg]="#aa7446"

# Color of inactive/disabled text
theme[inactive_fg]="#ad9066"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#c5b191"

# Cpu box outline color
theme[cpu_box]="#ad9066"

# Memory/disks box outline color
theme[mem_box]="#ad9066"

# Net up/down box outline color
theme[net_box]="#ad9066"

# Processes box outline color
theme[proc_box]="#ad9066"

# Box divider line and small boxes line color
theme[div_line]="#ad9066"

# Temperature graph colors
theme[temp_start]="#c7c5c2"
theme[temp_mid]="#a99e89"
theme[temp_end]="#ad9066"

# CPU graph colors
theme[cpu_start]="#c7c5c2"
theme[cpu_mid]="#a99e89"
theme[cpu_end]="#ad9066"

# Mem/Disk free meter
theme[free_start]="#c7c5c2"
theme[free_mid]="#a99e89"
theme[free_end]="#ad9066"

# Mem/Disk cached meter
theme[cached_start]="#c7c5c2"
theme[cached_mid]="#a99e89"
theme[cached_end]="#ad9066"

# Mem/Disk available meter
theme[available_start]="#c7c5c2"
theme[available_mid]="#a99e89"
theme[available_end]="#ad9066"

# Mem/Disk used meter
theme[used_start]="#c7c5c2"
theme[used_mid]="#a99e89"
theme[used_end]="#ad9066"

# Download graph colors
theme[download_start]="#c7c5c2"
theme[download_mid]="#a99e89"
theme[download_end]="#ad9066"

# Upload graph colors
theme[upload_start]="#c7c5c2"
theme[upload_mid]="#a99e89"
theme[upload_end]="#ad9066"
