[colors]
text       =#585149ff
message    =#585149ff
prompt     =#585149ff
placeholder=#585149ff
input      =#585149ff
# selection:foreground at 40 alpha
selection  =#58514940
background =#21170dff
# regular2
match          =#c5b191ff
selection-match=#c5b191ff
# regular4
border        =#bfbec2ff
counter       =#bfbec2ff
selection-text=#bfbec2ff
