[colors]
text       =#c7c5c2ff
message    =#c7c5c2ff
prompt     =#c7c5c2ff
placeholder=#c7c5c2ff
input      =#c7c5c2ff
# selection:foreground at 40 alpha
selection  =#c7c5c240
background =#21170dff
# regular2
match          =#c5b191ff
selection-match=#c5b191ff
# regular4
border        =#bfbec2ff
counter       =#bfbec2ff
selection-text=#bfbec2ff
