background_color=#21170d
timecode_color=#bfbec2
title_color=#bfbec2
time_pos_color=#bfbec2
buttons_color=#9f6d9e
small_buttonsL_color=#9f6d9e
small_buttonsR_color=#9f6d9e
top_buttons_color=#9f6d9e
held_element_color=#c7c5c2
time_pos_outline_color=#21170d
