set -g @base-color fg=#a99e89,bg=#21170d
set -g @flip-color fg=#21170d,bg=#a99e89

set -g window-status-format '#[fg=#21170d,bg=#a99e89] #W #[default]'
set -g window-status-current-format '#[fg=#21170d,bg=#9f6d9e] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'

