[colors]
text       =#c7c7c7ff
message    =#c7c7c7ff
prompt     =#c7c7c7ff
placeholder=#c7c7c7ff
input      =#c7c7c7ff
background =#212020ff
# regular2
match          =#ad8d6dff
selection-match=#ad8d6dff
# regular4
border        =#c3c0bcff
counter       =#c3c0bcff
selection-text=#c3c0bcff
# foreground at 40 alpha
selection=#c7c7c740

