
set -g @base-color fg=#c3c0bc,bg=#212020
set -g @flip-color fg=#212020,bg=#c3c0bc

set -g window-status-format '#[fg=#212020,bg=#c3c0bc] #W #[default]'
set -g window-status-current-format '#[fg=#212020,bg=#708dab] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'
