include=~/.config/autarky/current/theme/fuzzel_colors.ini
font = Iosevka NF:size=15
use-bold = yes

terminal = foot

prompt = ""
message = "App Search"

icons-enabled = yes
icon-theme = Suru++-Asprómauros

sort-result = yes
match-counter = yes

# show derived options from the apps (like open file manager at a bookmark)
show-actions = no
list-executables-in-path = no

horizontal-pad = 40
vertical-pad = 30
line-height = 30
# prompt to options distance
inner-pad = 10

# hide search prompt (searching still works)
hide-prompt = no
# search prompt text
placeholder = "    search"

# shorten ad-hoc to number of options
minimal-lines = yes

# 1 to disable big image when closing in on target
image-size-ratio = 0.3

render-workers = 1
match-workers = 1

[border]
width = 5
radius = 8
selection-radius = 8


