# All the default Autarky aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/autarky/default/bash/rc

# temporal/testing stuff here, otherwise move to rc
function pixi_hook(){
  eval "$(pixi shell-hook)"
}

eval "$(starship init bash)"

