# All the default Autarky aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/autarky/default/bash/rc

HISTFILE=~/.bash_history
HISTSIZE=1000
HISTFILESIZE=1000

shopt -s nullglob # get null instead of "*.JPG"
shopt -s histappend # append instead of overwrite
shopt -s checkwinsize # recalculate window size
# PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# Add your own exports, aliases, and functions here.
# alias n='NO_COLOR=1 nnn'
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias t='tree -L 2'
alias publicip="curl -4s ifconfig.me | awk '{print $1}'"
# arch update mirror list
alias update_mirrors='sudo reflector --protocol https --verbose --latest 25 --sort rate --save /etc/pacman.d/mirrorlist'

export PATH="$HOME/.cargo/bin:$PATH"

function pixi_hook(){
  eval "$(pixi shell-hook)"
}
# edit pixi env config to not alter ps1
function pixi_trim_ps1(){
  pixi config set shell.change-ps1 false
}
# change image for fastfetch
function fastfetch_switch_waifu(){
  # defaults to sfw/non-animated
  # n/sfw gif/nongif
  kind=${1:-sfw}
  animated=${2:-nongif}
  source ~/.config/fastfetch/change_waifu.sh $kind $animated
}

n() {
    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
    export NNN_TRASH=trash-put

    nnn -C "$@"

    if [ -f "$NNN_TMPFILE" ]; then
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE"
    fi
}

# FZF testing
export FZF_COMPLETION_TRIGGER='**'
export FZF_DEFAULT_OPTS="
--layout reverse
--border
--color=fg:7,bg:0,fg+:0,bg+:7,hl:6,hl+:6,info:6,prompt:6,\
pointer:5,marker:5,spinner:5,border:5,separator:0
"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow"

# this is to prevent quarto from updating latex packages by itself, which clashes with arch's handling of them
export TEXMFHOME=/var/empty
export TEXMFVAR=/var/empty
export TEXMFCONFIG=/var/empty


eval "$(starship init bash)"

