# All the default Autarky aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/autarky/default/bash/rc

# temporal/testing stuff here, otherwise move to rc
function pixi_hook(){
  eval "$(pixi shell-hook)"
}

# Added by LM Studio CLI (lms)
export PATH="$PATH:/home/fdo/.lmstudio/bin"
# End of LM Studio CLI section
export PATH=/home/fdo/.opencode/bin:$PATH

eval "$(starship init bash)"

PROMPT_COMMAND+=('TMPDIR="$PWD"')
