# ~/.tmux.conf
# don't fuck up colors unless necessary
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ",xterm-256color:Tc"

# clipboard
set -g set-clipboard on
set -g history-limit 100200 # only plain ints, so 100200 for readability

# Use Ctrl-a instead of Ctrl-b as prefix (like GNU screen)
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Split panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
unbind '"'
unbind %

# Resize panes with Alt + arrow keys
bind -n M-Left resize-pane -L 4
bind -n M-Right resize-pane -R 4
bind -n M-Up resize-pane -U 4
bind -n M-Down resize-pane -D 4

# pop pane to a new tab
bind p break-pane

# tabbing and renaming windows(tabs)
# bind -n C-Tab select-pane -t :.+
bind -n C-Tab select-window -n
bind -n C-BTab select-window -p
bind r command-prompt "rename-window '%%'"

# Enable mouse support
set -g mouse on

# Start windows and panes at 1 (not 0)
set -g base-index 1
setw -g pane-base-index 1

# Status bar
set -g status-position top
set -g status-interval 5

set -g @base-color fg=blue,bg=black

set -g status-style '#{@base-color}'
set -g message-style '#{@base-color}'
set -g message-command-style '#{@base-color}'
set -g mode-style '#{@base-color}'

set -g window-status-separator ''
set -g window-status-style '#{@base-color}'
set -g window-status-format '\
#[fg=black,bg=blue] #W #[default]'
set -g window-status-current-format '\
#[fg=black,bg=cyan] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'

set -g status-left-style fg=black,bg=blue
set -g status-left ' #(echo "#S" | tr '[:lower:]' '[:upper:]') '
set -g status-left-length 80

set -g status-right-style fg=black,bg=blue
set -g status-right '\
 #(date "+%b %d %H:%M" | tr "[:lower:]" "[:upper:]") \
@#(echo "#H" | tr "[:lower:]" "[:upper:]") '
set -g status-right-length 80

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
