# All the default Autarky aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/autarky/default/zsh/rc

HISTFILE=~/.zhistfile
HISTSIZE=1000
SAVEHIST=1000
# Add your own exports, aliases, and functions here.
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias t='tree -L 2'
alias publicip="curl -4s ifconfig.me | awk '{print $1}'"
# arch update mirror list
alias update_mirrors='sudo reflector --protocol https --verbose --latest 25 --sort rate --save /etc/pacman.d/mirrorlist'

function pixi_hook(){
  eval "$(pixi shell-hook)"
}
# edit pixi env config to not alter ps1
function pixi_trim_ps1(){
  pixi config set shell.change-ps1 false
}
# change image for fastfetch
function fastfetch_switch_waifu(){
  # defaults to sfw/neko
  kind=${1:-sfw}
  repo=${2:-neko}
  source ~/.config/fastfetch/change_waifu.sh $kind $repo
}

source /usr/share/zsh/plugins/zsh-vi-mode/zsh-vi-mode.plugin.zsh
eval "$(starship init zsh)"
