[colors]
text       =#4b5159ff
message    =#4b5159ff
prompt     =#4b5159ff
placeholder=#4b5159ff
input      =#4b5159ff
# selection:foreground at 40 alpha
selection  =#4b515940
background =#0f1822ff
# regular2
match          =#6590deff
selection-match=#6590deff
# regular4
border        =#e587cfff
counter       =#e587cfff
selection-text=#e587cfff
