background_color=#0f1822
timecode_color=#e587cf
title_color=#e587cf
time_pos_color=#e587cf
buttons_color=#da55a8
small_buttonsL_color=#da55a8
small_buttonsR_color=#da55a8
top_buttons_color=#da55a8
held_element_color=#4b5159
time_pos_outline_color=#0f1822
