set -g @base-color fg=#4853d8,bg=#0f1822
set -g @flip-color fg=#0f1822,bg=#4853d8

set -g window-status-format '#[fg=#0f1822,bg=#4853d8] #W #[default]'
set -g window-status-current-format '#[fg=#0f1822,bg=#da55a8] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'

