[colors]
text       =#545742ff
message    =#545742ff
prompt     =#545742ff
placeholder=#545742ff
input      =#545742ff
# selection:foreground at 40 alpha
selection  =#54574240
background =#1b1f03ff
# regular2
match          =#6590a7ff
selection-match=#6590a7ff
# regular4
border        =#2877a9ff
counter       =#2877a9ff
selection-text=#2877a9ff
