background_color=#1b1f03
timecode_color=#2877a9
title_color=#2877a9
time_pos_color=#2877a9
buttons_color=#b9bdc2
small_buttonsL_color=#b9bdc2
small_buttonsR_color=#b9bdc2
top_buttons_color=#b9bdc2
held_element_color=#545742
time_pos_outline_color=#1b1f03
