set -g @base-color fg=#98a3a9,bg=#1b1f03
set -g @flip-color fg=#1b1f03,bg=#98a3a9

set -g window-status-format '#[fg=#1b1f03,bg=#98a3a9] #W #[default]'
set -g window-status-current-format '#[fg=#1b1f03,bg=#b9bdc2] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'

