# Configure nnn with environment variables
NNN_PLUG='o:fzopen;m:nmount;t:xdgdefault;k:pskill'
NNN_FIFO=/tmp/nnn.fifo
NNN_TRASH=trash-put
NNN_ARCHIVE="\.(7z|bz2|gz|tar|tgz|zip|rar)$"
NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

# export NNN_PREVIEW=1
# Bookmarks
NNN_BMS='t:~/.local/share/Trash/files;d:~/Downloads;h:/run/media/fdo/Hoyle'

EDITOR=nvim
VISUAL=nvim

