[colors]
text       =#c7c6c5ff
message    =#c7c6c5ff
prompt     =#c7c6c5ff
placeholder=#c7c6c5ff
input      =#c7c6c5ff
selection  =#c7c6c540
background =#211b1aff
# selection: foreground at 40 alpha
# regular2
match          =#a7a19bff
selection-match=#a7a19bff
# regular4
border        =#a8bdc1ff
counter       =#a8bdc1ff
selection-text=#a8bdc1ff

