
set -g @base-color fg=#a8bdc1,bg=#211b1a
set -g @flip-color fg=#211b1a,bg=#a8bdc1

set -g window-status-format '#[fg=#211b1a,bg=#a8bdc1] #W #[default]'
set -g window-status-current-format '#[fg=#211b1a,bg=#be95a2] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'
