
set -g @base-color fg=#c1bc98,bg=#211007
set -g @flip-color fg=#211007,bg=#c1bc98

set -g window-status-format '#[fg=#211007,bg=#c1bc98] #W #[default]'
set -g window-status-current-format '#[fg=#211007,bg=#6f96a4] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'
