[colors]
text       =#c7c4c2ff
message    =#c7c4c2ff
prompt     =#c7c4c2ff
placeholder=#c7c4c2ff
input      =#c7c4c2ff
selection  =#c7c4c240
background =#21160bff
# selection: foreground at 40 alpha
# regular2
match          =#aa7b4bff
selection-match=#aa7b4bff
# regular4
border        =#ab8e68ff
counter       =#ab8e68ff
selection-text=#ab8e68ff

