
set -g @base-color fg=#ab8e68,bg=#21160b
set -g @flip-color fg=#21160b,bg=#ab8e68

set -g window-status-format '#[fg=#21160b,bg=#ab8e68] #W #[default]'
set -g window-status-current-format '#[fg=#21160b,bg=#a9aa99] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'
