[colors]
text       =#c9c8c8ff
message    =#c9c8c8ff
prompt     =#c9c8c8ff
placeholder=#c9c8c8ff
input      =#c9c8c8ff
background =#272424ff
# regular2
match          =#c5a19bff
selection-match=#c5a19bff
# regular4
border        =#769eaaff
counter       =#769eaaff
selection-text=#769eaaff
# foreground at 40 alpha
selection=#c9c8c840

