
set -g @base-color fg=#769eaa,bg=#272424
set -g @flip-color fg=#272424,bg=#769eaa

set -g window-status-format '#[fg=#272424,bg=#769eaa] #W #[default]'
set -g window-status-current-format '#[fg=#272424,bg=#9fa3a5] #(echo #W | tr '[:lower:]' '[:upper:]') #[default]'
